# Vectorization

Vectorization is the art of getting rid of explicit for loops your code

In [1]:
import numpy as np

a = np.array([1,2,3,4])

print (a)


[1 2 3 4]


In [4]:
import time 

a = np.random.rand(10000)
b = np.random.rand(10000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print (c)
print ("Vectorized version:"+ str(1000*(toc-tic))+ "ms")

c = 0
tic = time.time()
for i in range(10000):
    c += a[i]*b[i]
toc = time.time()

print (c)
print ("For loop:"+ str(1000*(toc-tic))+ "ms")

2452.6364404560263
Vectorized version:0.23889541625976562ms
2452.63644045603
For loop:39.61825370788574ms


# Broadcasting

Converting a single number into a vector (for math operations) (autoexpansion of the number)


In [6]:
import numpy as np

A = np.array ([[56.0, 0.0, 4.4, 68.0],
               [1.2, 104.0, 52.0, 8.0],
               [1.8, 135.0, 99.0, 0.9]])
print (A)

cal = A.sum(axis=0)
print (cal)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [10]:
#rank 1 array
a = np.random.randn(5)
print(a.shape)
#reshape
a = a.reshape(5,1)

#column vector
a = np.random.randn(5,1)
print(a.shape)

#for verification
assert(a.shape ==(5,1))

(5,)
(5, 1)
